name: Extract GIRA EMEL Open Data BSS availability data

on:
    schedule:
      - cron: "0 6,10,13,15,18,22,2,4 * * *"  # Runs at 6am, 10am, 1pm, 3pm, 6pm, 10pm, 2am, 4am UTC
    workflow_dispatch:  # Allows manual execution

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: |
        python dispo_gira.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update GIRA EMEL Open Data
        branch: ${{ github.head_ref }}
        file_pattern: "data_export/*.csv"
